#!/bin/bash
# NOTES: This script is for initializing dir structure (file systems' structure). pls execute below in your shell env at the root dir in your pj.
# commands
# 1. chmod +x create_project_structure.sh
# 2. ./create_project_structure.sh

set -eu

# PJ dir's entry list.
entries=(
  ".github/"
  ".github/workflows/"
  ".github/workflows/ci-cd.yaml"
  ".github/workflows/lint-go.yaml"
  ".github/workflows/lint-node.yaml"
  ".github/workflows/lint-python.yaml"
  ".github/workflows/e2e-playwright.yaml"
  ".github/workflows/kube-bench.yaml"
  ".github/workflows/kube-linter.yaml"
  ".github/workflows/trivy.yaml"
  ".github/workflows/policy-gatekeeper.yaml"
  "cicd/"
  "cicd/argocd-apps/"
  "cicd/argocd-apps/user-service-app.yaml"
  "cicd/argocd-apps/video-service-app.yaml"
  "cicd/argocd-apps/chat-service-app.yaml"
  "cicd/opa-policies/"
  "cicd/opa-policies/require-label.rego"
  "cicd/opa-policies/deny-privileged.rego"
  "cicd/gatekeeper-constraints/"
  "cicd/gatekeeper-constraints/require-label.yaml"
  "cicd/gatekeeper-constraints/deny-privileged.yaml"
  "cicd/README.md"
  "docs/"
  "docs/architecture.md"
  "docs/api/"
  "docs/api/openapi-user.yaml"
  "docs/api/openapi-video.yaml"
  "docs/api/openapi-chat.yaml"
  "docs/security.md"
  "docs/db.md"
  "docs/operations.md"
  "docs/cicd.md"
  "docs/monitoring.md"
  "docs/infra-terraform.md"
  "docs/infra-helm.md"
  "docs/infra-k8s.md"
  "docs/infra-network.md"
  "docs/infra-secrets.md"
  "docs/infra-dr.md"
  "docs/infra-observability.md"
  "docs/infra-compliance.md"
  "docs/infra-cost.md"
  "docs/infra-automation.md"
  "docs/infra-migration.md"
  "docs/infra-storage.md"
  # 必要に応じて
  "docs/infra-network-advanced.md"
  "docs/infra-security-advanced.md"
  "docs/infra-performance.md"
  "docs/infra-incident.md"
  "docs/README.md"
  "infra/"
  "infra/terraform/"
  "infra/terraform/main.tf"
  "infra/terraform/variables.tf"
  "infra/terraform/outputs.tf"
  "infra/terraform/provider.tf"
  "infra/terraform/eks.tf"
  "infra/terraform/alb.tf"
  "infra/terraform/rds.tf"
  "infra/terraform/iam.tf"
  "infra/terraform/s3.tf"
  "infra/terraform/cloudwatch.tf"
  "infra/terraform/README.md"
  "infra/helm/"
  "infra/helm/istio/"
  "infra/helm/istio/values.yaml"
  "infra/helm/prometheus/"
  "infra/helm/prometheus/values.yaml"
  "infra/helm/grafana/"
  "infra/helm/grafana/values.yaml"
  "infra/helm/gatekeeper/"
  "infra/helm/gatekeeper/values.yaml"
  "infra/k8s/"
  "infra/k8s/user-service/"
  "infra/k8s/user-service/deployment.yaml"
  "infra/k8s/user-service/service.yaml"
  "infra/k8s/user-service/ingress.yaml"
  "infra/k8s/user-service/hpa.yaml"
  "infra/k8s/user-service/pdb.yaml"
  "infra/k8s/user-service/secret.yaml"
  "infra/k8s/video-service/"
  "infra/k8s/video-service/deployment.yaml"
  "infra/k8s/video-service/service.yaml"
  "infra/k8s/video-service/ingress.yaml"
  "infra/k8s/video-service/hpa.yaml"
  "infra/k8s/video-service/pdb.yaml"
  "infra/k8s/video-service/secret.yaml"
  "infra/k8s/chat-service/"
  "infra/k8s/chat-service/deployment.yaml"
  "infra/k8s/chat-service/service.yaml"
  "infra/k8s/chat-service/ingress.yaml"
  "infra/k8s/chat-service/hpa.yaml"
  "infra/k8s/chat-service/pdb.yaml"
  "infra/k8s/chat-service/secret.yaml"
  "infra/k8s/istio/"
  "infra/k8s/istio/gateway.yaml"
  "infra/k8s/istio/virtualservice.yaml"
  "infra/k8s/istio/destinationrule.yaml"
  "infra/k8s/istio/authorizationpolicy.yaml"
  "infra/k8s/istio/requestauthentication.yaml"
  "infra/k8s/db/"
  "infra/k8s/db/rds-operator.yaml"
  "infra/k8s/db/secret.yaml"
  "infra/k8s/monitoring/"
  "infra/k8s/monitoring/prometheus.yaml"
  "infra/k8s/monitoring/grafana.yaml"
  "infra/k8s/monitoring/kiali.yaml"
  "infra/k8s/monitoring/cloudwatch-agent.yaml"
  "src/"
  "src/user-service/"
  "src/user-service/main.go"
  "src/user-service/Dockerfile"
  "src/user-service/go.mod"
  "src/user-service/README.md"
  "src/user-service/tests/"
  "src/user-service/tests/unit/"
  "src/user-service/tests/unit/user_handler_test.go"
  "src/user-service/tests/unit/user_model_test.go"
  "src/user-service/tests/integration/"
  "src/user-service/tests/integration/user_db_test.go"
  "src/user-service/tests/e2e/"
  "src/user-service/tests/e2e/user_api_test.go"
  "src/video-service/"
  "src/video-service/app.js"
  "src/video-service/Dockerfile"
  "src/video-service/package.json"
  "src/video-service/README.md"
  "src/video-service/tests/"
  "src/video-service/tests/unit/"
  "src/video-service/tests/unit/videoController.test.js"
  "src/video-service/tests/unit/videoModel.test.js"
  "src/video-service/tests/integration/"
  "src/video-service/tests/integration/videoDb.test.js"
  "src/video-service/tests/e2e/"
  "src/video-service/tests/e2e/videoApi.test.js"
  "src/chat-service/"
  "src/chat-service/main.py"
  "src/chat-service/Dockerfile"
  "src/chat-service/requirements.txt"
  "src/chat-service/README.md"
  "src/chat-service/tests/"
  "src/chat-service/tests/unit/"
  "src/chat-service/tests/unit/test_chat_handler.py"
  "src/chat-service/tests/unit/test_chat_model.py"
  "src/chat-service/tests/integration/"
  "src/chat-service/tests/integration/test_chat_db.py"
  "src/chat-service/tests/e2e/"
  "src/chat-service/tests/e2e/test_chat_api.py"
  "scripts/"
  "scripts/db-migrate.sh"
  "scripts/deploy.sh"
  "scripts/cleanup.sh"
  ".env.example"
  "README.md"
  "Makefile"
)

for entry in "${entries[@]}"; do
  # In case of dir:
  if [[ "$entry" =~ /$ ]]; then
    if [ ! -d "$entry" ]; then
      echo "Creating directory: $entry"
      mkdir -p "$entry"
    fi
  else
    dir=$(dirname "$entry")
    if [ ! -d "$dir" ]; then
      echo "Creating parent directory: $dir"
      mkdir -p "$dir"
    fi
    if [ ! -f "$entry" ]; then
      echo "Creating file: $entry"
      touch "$entry"
    fi
  fi
done

echo "プロジェクト構造の作成が完了しました。"
